<?php

namespace Database\Seeders;

use App\Models\District;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $districtsArray = [
            "Cruzeiro do Sul" => [
                "Centro",
                "Aeroporto Velho",
                "Miritizal",
                "Boca da Alemanha",
                "Telégrafo",
                "Saboeiro",
                "São José",
                "Olivença"
            ],
            "Rio Branco" => [
                "Loteamento Fahat",
                "Santa Helena",
                "Major Mendonça",
                "Vila da Amizade (Loteamento Acauã)",
                "Vila Acre",
                "Ramal Bom Jesus (Vila Billar, Luiz Ângelo, Vila Boa Vontade, Ramal do Mineiro e Vila do Marcelo)",
                "Ramal Bom Futuro",
                "Vila Benfica",
                "Vila Jerusalém",
                "Santa Maria",
                "Itucumã",
                "Loteamento Mora Bem",
                "Loteamento Sol Nascente",
                "Beco Buritizal",
                "Recanto dos Buritis",
                "Santa Inês",
                "Recanto da Judia",
                "Jacarandá",
                "Conjunto Rosalina I",
                "Conjunto Rosalinda II",
                "Conjunto Rosalinda III",
                "Belo Jardim I",
                "Belo Jardim II",
                "Belo Buritis",
                "Loteamento Herculano",
                "Vila Belo Jardim",
                "Vila Santa Cecília",
                "Vila Albert Sampaio",
                "Vila Liberdade",
                "Santo Afonso",
                "Recanto da Judia",
                "06 de Agosto",
                "Amapá",
                "Cidade Nova",
                "Comara",
                "Loteamento Alzira Cruz",
                "Loteamento Praia do Amapá",
                "Bairro do Quinze",
                "Taquari",
                "Triângulo Novo",
                "Triângulo Velho",
                "Areal",
                "Conjunto Canaã",
                "Ramal Menino Jesus (Pólo)",
                "Loteamento Girassol",
                "Bairro 10 de Junho",
                "Adalberto Aragão",
                "Aviário",
                "Baixa da Colina",
                "Baixa da Habitasa",
                "Base",
                "Cohab do Bosque",
                "Baixa da Cadeia Velha",
                "Capoeira",
                "Cerâmica",
                "Conjunto Jardim São Francisco",
                "Dom Giocondo",
                "Alegria",
                "Jardim Tropical",
                "Morada do Sol",
                "Cadeia Velha (Do Varejão ao Senai)",
                "Loteamento São José",
                "Procon",
                "Solar",
                "Vila Ivonete",
                "Bosque",
                "José Augusto",
                "Ipase",
                "Guiomard Santos",
                "Habitasa",
                "Oscar Passos",
                "Vitória",
                "Novo Residencial Eldorado",
                "Chico Mendes",
                "Conjunto Mutambo",
                "Eldorado II",
                "Novo Eldorado",
                "Conjunto Angico",
                "Placas",
                "Loteamento Guanabara",
                "Apolônio Sales",
                "Loteamento Altamira",
                "Loteamento São Francisco",
                "Residencial Vale do Açai",
                "Conjunto Ouricuri",
                "Residencial Iaco",
                "Conjunto Edson Cadaxo",
                "Loteamento Jaguar",
                "Residencial Andirá",
                "Residencial São Jorge",
                "Residencial Santa Cruz",
                "Parque dos Sábias",
                "Tancredo Neves",
                "Jorge Lavocat",
                "Defesa Civil",
                "Irineu serra",
                "Montanhês",
                "Conjunto Jarbas Passarinho",
                "Adalberto Sena",
                "Alto Alegre",
                "Juarez Távora",
                "Novo Horizonte",
                "Raimundo Melo",
                "Vila Nova",
                "Xavier Maia",
                "Loteamento Santo",
                "Wanderley Dantas",
                "Conjunto Mulateiro",
                "Loteamento Dal Pascualy",
                "Conjunto Genipapo",
                "Caladinho",
                "Loteamento Copacabana",
                "Loteamento Céu Azul",
                "Loteamento Santa Monica",
                "Conjunto Copaiba",
                "Conjunto Andiroba",
                "Conjunto Macauã",
                "Conjunto Andira",
                "Tangara",
                "Conjunto Universitario",
                "Conquista",
                "Custodio Freire",
                "Estação Experimental",
                "Geraldo Fleming ",
                "Jardim América",
                "Isaura Parente ",
                "Mocinha Magalhães ",
                "Bairro da Paz ",
                "Parque das Palmeiras ",
                "Residencial Joafra ",
                "Santa Quitéria ",
                "Nova Estação",
                "Conjunto Mariana ",
                "Barro Vermelho",
                "Conjunto Paulo Cesar",
                "Conjunto Rui Lino",
                "Distrito Industrial",
                "Hélio Melo",
                "Loteamento Isaura Parente",
                "Conjunto Manoel Julião",
                "Monte Alto",
                "Residencial Vila Mariana",
                "Residencial Iolanda",
                "Residencial Petrópolis",
                "Tucumã ",
                "Santa Terezinha",
                "Boa Esperança",
                "Vila Aquiles Peret",
                "Jardim Primavera",
                "Loteamento dos Engenheiros  ",
                "Loteamento Flora",
                "Loteamento Jardim Brasil",
                "Abrahão Alab",
                "Castelo Branco",
                "Conjunto Esperança I",
                "Conjunto Esperança II",
                "Conjunto Bela Vista",
                "Ivete Vargas",
                "Novo Horizonte",
                "Residencial Maria Iris",
                "Conjunto Nova Esperança",
                "Conjunto Habitar Brasil",
                "Floresta Sul",
                "Floresta Norte",
                "Mascarenhas de Moraes",
                "Jardim Alah ",
                "Jardim Europa",
                "Conjunto Esperança III",
                "Betel II",
                "Doca Furtado",
                "Betel I (Osvaldo Amorim)",
                "LBA",
                "Loteamento Ana Rosa",
                "Loteamento Antonio Macedo ",
                "Conjunto Aroeira",
                "Conjunto Israel Lira",
                "Loteamento João Carlos",
                "São Miguel",
                "Ilson Ribeiro",
                "Portal da Amazônia I, II e III ",
                "Laélia Alcântara",
                "Novo Conjunto Ilson Ribeiro",
                "Conjunto Village Tiradentes",
                "Waldemar Maciel ",
                "Conjunto Itatiaia",
                "Nova Morada",
                "Conjunto Jequitibá",
                "Loteamento Raimundo Maia",
                "Novo Calafate",
                "Pedro Roseno",
                "Aeroporto Velho",
                "Ayrton Sena",
                "Bahia Nova ",
                "Bahia Velha",
                "Boa União",
                "Boa Vista",
                "Glória",
                "João Eduardo I",
                "João Eduardo II",
                "João Paulo I",
                "Loteamento Santo Afonso I",
                "Loteamento São Sebastião",
                "Palheiral",
                "Pista",
                "Preventório",
                "Plácido de Castro",
                "Sobral",
                "Conjunto de Castro",
                "Conjunto Cabreúva",
                "POLO WILSON PINHEIRO",
                "POLO GERALDO MESQUITA",
                "VILA MANOEL MARQUES",
                "PA MORENO MAIA",
                "COMUNIDADE ÁGUA PRETA",
                "BARRO ALTO",
                "ESTRADA TRANSACREANA, KM 05 – RAMAL UNIÃO",
                "COMUNIDADE UNIÃO FLORESTA",
                "PA ITAMARATY RAMAL JARINAL",
                "ESCONDIDO II RAMAL SABÓIA",
                "RAMAL CENTRINHO",
                "VILA VERDE",
                "RAMAL DO BEIJA FLOR",
                "RAMAL DO LIBERDADE KM 05",
                "RAMAL CASTANHEIRA",
                "PA CARÃO , KM 52",
                "PA CARÃO,KM 42",
                "PA CARÃO,KM 40 ",
                "PA CARÃO – RAMAL PRIMAVERA",
                "PA CARÃO – RAMAL DA PELADEIRA KM 06",
                "ESTRADA TRANSACREANA KM 91 – RAMAL DO ANTIMARY KM  ",
                "RAMAL CENTRINHO",
                " RAMAL MAÇARANDUBA KM 06  ",
                "RAMAL RIO BRANCO DA CAPELA KM 20",
                "RAMAL DO ESPALHA KM 12",
                "RAMAL DO VAI SE VER KM 18",
                "PA ORIENTE KM 140",
                "RAMAL OLHO D´ÁGUA KM 06",
                "COMUNIDADE ITAMARATY II",
                "ESTRADA TRANSACREANA KM 80",
                "REGIONAIS TRANSACREANA I E II",
                "ESTRADA DO QUIXADÁ",
                "ESTRADA DO QUIXADÁ – RAMAL BOA ÁGUA",
                "BR 364, KM 08 AO LADO DO AEROPORTO",
                "ESTRADA JARBAS PASSARINHO",
                "ESTRADA DO QUIXADÁ RAMAL DO LIMOEIRO",
                "ESTRADA DO SÃO FRANCISCO RAMAL PANORAMA KM 06 ",
                "ESTRADA JARBAS PASSARINHO ,KM 06 RAMAL SÃO RAIMUNDO",
                "AC, KM 20 – RAMAL SÃO PEDRO ",
                "BR 364, KM 17 – CUSTÓDIO FREIRE RAMAL CASTANHETA ",
                "ESTRADA AC 10, KM 19 – POLO GERALDO MESQUITA",
                "BR 364, KM 08 – RAMAL DO ROMÃO KM 03",
                "ESTRADA DO BARRO VERMELHO KM 09",
                "ESTRADA DO QUIXADÁ KM 12 – RAMAL EXTREMA KM 03",
                "BR 364,KM 06 – ESTRADA DO AEROPORTO ",
                "ESTRADA DE PORTO ACRE,KM 14 – RAMAL SANTOS KM 10",
                "ESTRADA DO PIRANJI",
                "ESTRADA DE PORTO ACRE  - RAMAL MEDEIROS",
                "ESTRADA DO LIMOEIRO – RAMAL ORIENTE",
                "PA ORIENTE KM 140",
                "BELO JARDIM I II III",
                "RAMAL DO CLODOALDO",
                "BENFICA – RAMAL PALHEIRA",
                "ESTRADA DE BOCA DO ACRE",
                "RAMAL DA ZEZÉ",
                "RODOVIA AC 40 RAMAL ITUCUMÃ",
                "RAMAL DO MOREIRA",
                "RAMAL BENFICA",
                "RAMAL GALILÉIA",
                "ESTRADA DO AMAPÁ – RAMAL SANTA HELENA",
                "RAMAL DO CACAU",
                "RAMAL BELO JARDIM",
                "ESTRADA DEBOCADO ACRE KM 25",
                "ESTRADA DE BOCA DO ACRE KM 28",
                "RAMAL ASTRO REIS",
                "RAMAL BEIRA RIO",
                "RAMAL SÃO JOSÉ",
                "RAMAL DO BRÁZ",
                "RAMAL DO PALHEIRA",
                "RAMAL DA GARAPEIRA"
            ],
            "Sena Madureira" => [
                "Centro",
                "Bom Sucesso",
                "Cristo Libertador",
                "São Francisco",
                "Pista"
            ],
            "Tarauacá" => [
                "Centro",
                "Triângulo",
                "Copacabana",
                "Senador Pompeu",
                "Aeroporto"
            ],
            "Feijó" => [
                "Centro",
                "Esperança",
                "Geraldo Mesquita",
                "Terminal"
            ],
            "Brasiléia" => [
                "Centro",
                "Eldorado",
                "José Rabelo",
                "Satélite"
            ],
            "Epitaciolândia" => [
                "Centro",
                "Beira Rio",
                "Aeroporto",
                "José Hassem"
            ],
            "Xapuri" => [
                "Centro",
                "Laranjal",
                "Bairro Braga Sobrinho",
                "Constantino"
            ],
            "Plácido de Castro" => [
                "Centro",
                "Cidade Nova",
                "Taquari"
            ],
            "Senador Guiomard" => [
                "Centro",
                "São Francisco",
                "Quinari"
            ],
            "Acrelândia" => [
                "Centro",
                "Porto Acre",
                "Planalto"
            ],
            "Porto Acre" => [
                "Centro",
                "Vila do Incra",
                "Boca do Acre"
            ]
        ];

        foreach ($districtsArray as $key => $items) {
            foreach ($items as $item) {
                $district = new District();

                $district->city = $key;
                $district->name = $item;

                $district->save();
            }
        }
    }
}
