<?php

namespace Database\Seeders;

use App\Models\District;
use App\Models\Regional;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RegionalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $regionals = [
            "VILA ACRE" => [
                1 => "Loteamento Fahat",
                2 => "Santa Helena",
                3 => "Major Mendonça",
                4 => "Vila da Amizade (Loteamento Acauã)",
                5 => "Vila Acre",
                6 => "Ramal Bom Jesus (Vila Billar, Luiz Ângelo, Vila Boa Vontade, Ramal do Mineiro e Vila do Marcelo)",
                7 => "Ramal Bom Futuro",
                8 => "Vila Benfica",
                9 => "Vila Jerusalém",
                10 => "Santa Maria",
                11 => "Itucumã",
                12 => "Loteamento Mora Bem",
                13 => "Loteamento Sol Nascente",
                14 => "Beco Buritizal"
            ],
            "BELO JARDIM" => [
                1 => "Recanto dos Buritis",
                2 => "Santa Inês",
                3 => "Recanto da Judia",
                4 => "Jacarandá",
                5 => "Conjunto Rosalina I",
                6 => "Conjunto Rosalinda II",
                7 => "Conjunto Rosalinda III",
                8 => "Belo Jardim I",
                9 => "Belo Jardim II",
                10 => "Belo Buritis",
                11 => "Loteamento Herculano",
                12 => "Vila Belo Jardim",
                13 => "Vila Santa Cecília",
                14 => "Vila Albert Sampaio",
                15 => "Vila Liberdade",
                16 => "Santo Afonso",
                17 => "Recanto da Judia"
            ],
            "06 DE AGOSTO" => [
                1 => "06 de Agosto",
                2 => "Amapá",
                3 => "Cidade Nova",
                4 => "Comara",
                5 => "Loteamento Alzira Cruz",
                6 => "Loteamento Praia do Amapá",
                7 => "Bairro do Quinze",
                8 => "Taquari",
                9 => "Triângulo Novo",
                10 => "Triângulo Velho",
                11 => "Areal",
                12 => "Conjunto Canaã",
                13 => "Ramal Menino Jesus (Pólo)",
                14 => "Loteamento Girassol"
            ],
            "CADEIA VELHA" => [
                1 => "Bairro 10 de Junho",
                2 => "Adalberto Aragão",
                3 => "Aviário",
                4 => "Baixa da Colina",
                5 => "Baixa da Habitasa",
                6 => "Base",
                7 => "Cohab do Bosque",
                8 => "Baixa da Cadeia Velha",
                9 => "Capoeira",
                10 => "Cerâmica",
                11 => "Conjunto Jardim São Francisco",
                12 => "Dom Giocondo",
                13 => "Alegria",
                14 => "Jardim Tropical",
                15 => "Morada do Sol",
                16 => "Cadeia Velha (Do Varejão ao Senai)",
                17 => "Loteamento São José",
                18 => "Procon",
                19 => "Solar",
                20 => "Vila Ivonete",
                21 => "Bosque",
                22 => "José Augusto",
                23 => "Ipase",
                24 => "Guiomard Santos",
                25 => "Habitasa"
            ],
            "SÃO FRANCISCO" => [
                1 => "Oscar Passos",
                2 => "Vitória",
                3 => "Novo Residencial Eldorado",
                4 => "Chico Mendes",
                5 => "Conjunto Mutambo",
                6 => "Eldorado II",
                7 => "Novo Eldorado",
                8 => "Conjunto Angico",
                9 => "Placas",
                10 => "Loteamento Guanabara",
                11 => "Apolônio Sales",
                12 => "Loteamento Altamira",
                13 => "Loteamento São Francisco",
                14 => "Residencial Vale do Açai",
                15 => "Conjunto Ouricuri",
                16 => "Residencial Iaco",
                17 => "Conjunto Edson Cadaxo",
                18 => "Loteamento Jaguar",
                19 => "Residencial Andirá",
                20 => "Residencial São Jorge"
            ],
            "REGIONAL TANCREDO NEVES" => [
                1 => "Residencial Santa Cruz",
                2 => "Parque dos Sábias",
                3 => "Tancredo Neves",
                4 => "Jorge Lavocat",
                5 => "Defesa Civil",
                6 => "Irineu serra",
                7 => "Montanhês",
                8 => "Conjunto Jarbas Passarinho",
                9 => "Adalberto Sena",
                10 => "Alto Alegre",
                11 => "Juarez Távora",
                12 => "Novo Horizonte",
                13 => "Raimundo Melo",
                14 => "Vila Nova",
                15 => "Xavier Maia",
                16 => "Loteamento Santo",
                17 => "Wanderley Dantas",
                18 => "Conjunto Mulateiro",
                19 => "Loteamento Dal Pascualy",
                20 => "Conjunto Genipapo",
                21 => "Caladinho",
                22 => "Loteamento Copacabana",
                23 => "Loteamento Céu Azul",
                24 => "Loteamento Santa Monica",
                25 => "Conjunto Copaiba",
                26 => "Conjunto Andiroba",
                27 => "Conjunto Macauã",
                28 => "Conjunto Andira"
            ],
            "REGIONAL ESTAÇÃO EXPERIMENTAL" => [
                1 => "Tangara",
                2 => "Conjunto Universitario",
                3 => "Conquista",
                4 => "Custodio Freire",
                5 => "Estação Experimental",
                6 => "Geraldo Fleming ",
                7 => "Jardim América",
                8 => "Isaura Parente ",
                9 => "Mocinha Magalhães ",
                10 => "Bairro da Paz ",
                11 => "Parque das Palmeiras ",
                12 => "Residencial Joafra ",
                13 => "Santa Quitéria ",
                14 => "Nova Estação",
                15 => "Conjunto Mariana ",
                16 => "Barro Vermelho",
                17 => "Conjunto Paulo Cesar",
                18 => "Conjunto Rui Lino",
                19 => "Distrito Industrial",
                20 => "Hélio Melo",
                21 => "Loteamento Isaura Parente",
                22 => "Conjunto Manoel Julião",
                23 => "Monte Alto",
                24 => "Residencial Vila Mariana",
                25 => "Residencial Iolanda",
                26 => "Residencial Petrópolis",
                27 => "Tucumã ",
                28 => "Santa Terezinha",
                29 => "Boa Esperança",
                30 => "Vila Aquiles Peret",
                31 => "Jardim Primavera",
                32 => "Loteamento dos Engenheiros  ",
                33 => "Loteamento Flora",
                34 => "Loteamento Jardim Brasil",
            ],
            "REGIONAL FLORESTA" => [
                1 => "Abrahão Alab",
                2 => "Castelo Branco",
                3 => "Conjunto Esperança I",
                4 => "Conjunto Esperança II",
                5 => "Conjunto Bela Vista",
                6 => "Ivete Vargas",
                7 => "Novo Horizonte",
                8 => "Residencial Maria Iris",
                9 => "Conjunto Nova Esperança",
                10 => "Conjunto Habitar Brasil",
                11 => "Floresta Sul",
                12 => "Floresta Norte",
                13 => "Mascarenhas de Moraes",
                14 => "Jardim Alah ",
                15 => "Jardim Europa",
                16 => "Conjunto Esperança III",
                17 => "Betel II",
                18 => "Doca Furtado",
                19 => "Betel I (Osvaldo Amorim)",
                20 => "LBA",
                21 => "Loteamento Ana Rosa",
                22 => "Loteamento Antonio Macedo "
            ],
            "REGIONAL DO CALAFATE" => [
                1 => "Conjunto Aroeira",
                2 => "Conjunto Israel Lira",
                3 => "Loteamento João Carlos",
                4 => "São Miguel",
                5 => "Ilson Ribeiro",
                6 => "Portal da Amazônia I, II e III ",
                7 => "Laélia Alcântara",
                8 => "Novo Conjunto Ilson Ribeiro",
                9 => "Conjunto Village Tiradentes",
                10 => "Waldemar Maciel ",
                11 => "Conjunto Itatiaia",
                12 => "Nova Morada",
                13 => "Conjunto Jequitibá",
                14 => "Loteamento Raimundo Maia",
                15 => "Novo Calafate",
                16 => "Pedro Roseno",
            ],
            "REGIONAL DA BAIXADA" => [
                1 => "Aeroporto Velho",
                2 => "Ayrton Sena",
                3 => "Bahia Nova ",
                4 => "Bahia Velha",
                5 => "Boa União",
                6 => "Boa Vista",
                7 => "Glória",
                8 => "João Eduardo I",
                9 => "João Eduardo II",
                10 => "João Paulo I",
                11 => "Loteamento Santo Afonso I",
                12 => "Loteamento São Sebastião",
                13 => "Palheiral",
                14 => "Pista",
                15 => "Preventório",
                16 => "Plácido de Castro",
                17 => "Sobral",
                18 => "Conjunto de Castro",
                19 => "Conjunto Cabreúva",
            ],
            "REGIONAIS RURAIS" => [
                1 => "POLO WILSON PINHEIRO",
                2 => "POLO GERALDO MESQUITA",
                3 => "VILA MANOEL MARQUES",
                4 => "PA MORENO MAIA",
                5 => "COMUNIDADE ÁGUA PRETA",
                6 => "BARRO ALTO",
                7 => "ESTRADA TRANSACREANA, KM 05 – RAMAL UNIÃO",
                8 => "COMUNIDADE UNIÃO FLORESTA",
            ],
            "RREGIONAL TRANSACREANA II" => [
                1 => "PA ITAMARATY RAMAL JARINAL",
                2 => "ESCONDIDO II RAMAL SABÓIA",
                3 => "RAMAL CENTRINHO",
                4 => "VILA VERDE",
                5 => "RAMAL DO BEIJA FLOR",
                6 => "RAMAL DO LIBERDADE KM 05",
                7 => "RAMAL CASTANHEIRA",
                8 => "PA CARÃO , KM 52",
                9 => "PA CARÃO,KM 42",
                10 => "PA CARÃO,KM 40 ",
                11 => "PA CARÃO – RAMAL PRIMAVERA",
                12 => "PA CARÃO – RAMAL DA PELADEIRA KM 06",
                13 => "ESTRADA TRANSACREANA KM 91 – RAMAL DO ANTIMARY KM  ",
                14 => "RAMAL CENTRINHO",
                15 => " RAMAL MAÇARANDUBA KM 06  ",
                16 => "RAMAL RIO BRANCO DA CAPELA KM 20",
                17 => "RAMAL DO ESPALHA KM 12",
                18 => "RAMAL DO VAI SE VER KM 18",
                19 => "PA ORIENTE KM 140",
                20 => "RAMAL OLHO D´ÁGUA KM 06",
                21 => "COMUNIDADE ITAMARATY II",
                22 => "ESTRADA TRANSACREANA KM 80",
            ],
            "REGIONAL BACIA DO RIOZINHO DO RÔLA" => [
                1 => "REGIONAIS TRANSACREANA I E II",
            ],
            "REGIONAL 1º DISTRITO" => [
                1 => "ESTRADA DO QUIXADÁ",
                2 => "ESTRADA DO QUIXADÁ – RAMAL BOA ÁGUA",
                3 => "BR 364, KM 08 AO LADO DO AEROPORTO",
                4 => "ESTRADA JARBAS PASSARINHO",
                5 => "ESTRADA DO QUIXADÁ RAMAL DO LIMOEIRO",
                6 => "ESTRADA DO SÃO FRANCISCO RAMAL PANORAMA KM 06 ",
                7 => "ESTRADA JARBAS PASSARINHO ,KM 06 RAMAL SÃO RAIMUNDO",
                8 => "AC, KM 20 – RAMAL SÃO PEDRO ",
                9 => "BR 364, KM 17 – CUSTÓDIO FREIRE RAMAL CASTANHETA ",
                10 => "ESTRADA AC 10, KM 19 – POLO GERALDO MESQUITA",
                11 => "BR 364, KM 08 – RAMAL DO ROMÃO KM 03",
                12 => "ESTRADA DO BARRO VERMELHO KM 09",
                13 => "ESTRADA DO QUIXADÁ KM 12 – RAMAL EXTREMA KM 03",
                14 => "BR 364,KM 06 – ESTRADA DO AEROPORTO ",
                15 => "ESTRADA DE PORTO ACRE,KM 14 – RAMAL SANTOS KM 10",
                16 => "ESTRADA DO PIRANJI",
                17 => "ESTRADA DE PORTO ACRE  - RAMAL MEDEIROS",
                18 => "ESTRADA DO LIMOEIRO – RAMAL ORIENTE",
                19 => "PA ORIENTE KM 140",
            ],
            "REGIONAL 2º DISTRITO" => [
                1 => "BELO JARDIM I II III",
                2 => "RAMAL DO CLODOALDO",
                3 => "BENFICA – RAMAL PALHEIRA",
                4 => "ESTRADA DE BOCA DO ACRE",
                5 => "RAMAL DA ZEZÉ",
                6 => "RODOVIA AC 40 RAMAL ITUCUMÃ",
                7 => "RAMAL DO MOREIRA",
                8 => "RAMAL BENFICA",
                9 => "RAMAL GALILÉIA",
                10 => "ESTRADA DO AMAPÁ – RAMAL SANTA HELENA",
                11 => "RAMAL DO CACAU",
                12 => "RAMAL BELO JARDIM",
                13 => "ESTRADA DEBOCADO ACRE KM 25",
                14 => "ESTRADA DE BOCA DO ACRE KM 28",
                15 => "RAMAL ASTRO REIS",
                16 => "RAMAL BEIRA RIO",
                17 => "RAMAL SÃO JOSÉ",
                18 => "RAMAL DO BRÁZ",
                19 => "RAMAL DO PALHEIRA",
                20 => "RAMAL DA GARAPEIRA"
            ]
        ];

        foreach ($regionals as $key => $value) {
            $existentRegional = Regional::query()->where('name', $key)->first();
            $newRegional = $existentRegional ? $existentRegional : new Regional() ;
            $newRegional->name = $key;

            if ($newRegional->save()) {
                if (count($value) > 0) {
                    foreach ($value as $key2 => $value2) {

                        $existentDistrict = District::query()->where('name', $key2)->first();

                        if (!$existentDistrict) {
                            $newDistrict = new District();
                            $newDistrict->regional()->associate($newRegional);
                            $newDistrict->regional_order_number = $key2;
                            $newDistrict->name = $value2;

                            $newDistrict->save();
                        }
                    }
                }
            }

        }
    }
}
